stages:
  - deploy

deploy:
  stage: deploy
  image: alpine
  before_script:
    - apk add openssh-client
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
  script:
    - >
      ssh -o StrictHostKeyChecking=no $SERVER_ADDR
      "cd /home/summer/clash-back;
      sh gradlew bootJar;
      docker-compose build;
      docker-compose up -d;"