stages:
  - deploy

deploy:
  stage: deploy
  image: ubuntu:16.04
  before_script:
    - apt-get update -qq
    - apt-get install -qq git
    - 'which ssh-agent || ( apt install -qq openssh-client )'
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$SSH_PRIVATE_KEY" | base64 --decode)
    - mkdir -p ~/.ssh
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
  script:
    - >
      ssh -o StrictHostKeyChecking=no -o ConnectTimeout=120 $SERVER_ADDR
      "cd /home/summer/clash-back;
      sh gradlew bootJar;
      docker-compose build;
      docker-compose up -d;"