stages:
  - deploy

deploy:
  stage: deploy
  image: ubuntu:16.04
  before_script:
    - apt-get update -qq
    - apt-get install -qq git curl
    - 'which ssh-agent || ( apt install -qq openssh-client)'
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
  script:
    - ssh -o StrictHostKeyChecking=no summer@46.102.129.26 -A "cd ~; touch test.txt"